
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Vinorcola\PrivateUserBundle\:
        resource: '../src/*'
        exclude: '../src/{Data,Entity,Resources}'

    Vinorcola\PrivateUserBundle\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Vinorcola\PrivateUserBundle\Model\UserManagerInterface: '@Vinorcola\PrivateUserBundle\Model\UserManager'
